package models

import "time"

// TreasureChest represents a treasure chest in the system
type TreasureChest struct {
	ID              string    `json:"id"               db:"id"`               // UUID generated by DB
	Source          string    `json:"source"           db:"source"`           // Source of the chest
	QRMatch         string    `json:"qr_match"         db:"qr_match"`         // Auto-generated QR code (e.g., "1-ABC12345")
	IsSecure        bool      `json:"is_secure"        db:"is_secure"`        // Security flag
	Status          string    `json:"status"           db:"status"`           // Status: pending, claimed, expired
	FirstScore      int       `json:"first_score"      db:"first_score"`      // Score for first finder (owner)
	SubsequentScore int       `json:"subsequent_score" db:"subsequent_score"` // Score for subsequent finders (explorers)
	CreatedBy       string    `json:"created_by"       db:"created_by"`       // User who created this chest
	CreatedAt       time.Time `json:"created_at"       db:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"       db:"updated_at"`
}

// TreasureExplorer represents an explorer who can claim chests
type TreasureExplorer struct {
	ID        int       `json:"id"         db:"id"`         // Serial primary key
	ChestID   string    `json:"chest_id"   db:"chest_id"`   // UUID reference to chest
	PlayerID  int       `json:"player_id"  db:"player_id"`  // Reference to player
	Score     int       `json:"score"      db:"score"`      // Score earned for this chest
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

// TreasureOwner represents the owner/claimer of a chest
type TreasureOwner struct {
	ID        int       `json:"id"         db:"id"`         // Serial primary key
	ChestID   string    `json:"chest_id"   db:"chest_id"`   // UUID reference to chest (UNIQUE)
	PlayerID  int       `json:"player_id"  db:"player_id"`  // Reference to player
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

// Player represents a player in the system
type Player struct {
	ID          int       `json:"id"           db:"id"`           // Serial primary key
	Email       string    `json:"email"        db:"email"`        // Player email (unique)
	Name        string    `json:"name"         db:"name"`         // Player name
	PhoneNumber string    `json:"phone_number" db:"phone_number"` // Player phone
	CreatedAt   time.Time `json:"created_at"   db:"created_at"`
}
