package models

import "time"

// TreasureChest represents a treasure chest in the system
type TreasureChest struct {
	ID        string    `json:"id"         db:"id"`         // UUID generated by DB
	Source    string    `json:"source"     db:"source"`     // Source of the chest
	QRMatch   string    `json:"qr_match"   db:"qr_match"`   // Auto-generated QR code (e.g., "1-ABC12345")
	IsSecure  bool      `json:"is_secure"  db:"is_secure"`  // Security flag
	Status    string    `json:"status"     db:"status"`     // Status: pending, claimed, expired
	CreatedBy string    `json:"created_by" db:"created_by"` // User who created this chest
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// TreasureExplorer represents an explorer who can claim chests
type TreasureExplorer struct {
	ID          int       `json:"id"           db:"id"`           // Serial primary key
	ChestID     string    `json:"chest_id"     db:"chest_id"`     // UUID reference to chest
	Name        string    `json:"name"         db:"name"`         // Explorer name
	Email       string    `json:"email"        db:"email"`        // Explorer email
	PhoneNumber string    `json:"phone_number" db:"phone_number"` // Explorer phone
	CreatedAt   time.Time `json:"created_at"   db:"created_at"`
}

// TreasureOwner represents the owner/claimer of a chest
type TreasureOwner struct {
	ID          int       `json:"id"           db:"id"`           // Serial primary key
	ChestID     string    `json:"chest_id"     db:"chest_id"`     // UUID reference to chest (UNIQUE)
	Name        string    `json:"name"         db:"name"`         // Owner name
	Email       string    `json:"email"        db:"email"`        // Owner email
	PhoneNumber string    `json:"phone_number" db:"phone_number"` // Owner phone
	CreatedAt   time.Time `json:"created_at"   db:"created_at"`
}
