package repository

import (
	"context"

	"github.com/mihir/treasure-hunt-backend/internal/models"
)

// TreasureChestRepository defines the interface for treasure chest data operations
type TreasureChestRepository interface {
	// Create creates a new treasure chest (ID and QRMatch auto-generated by DB)
	Create(ctx context.Context, chest *models.TreasureChest) error

	// CreateBatch creates multiple treasure chests with the same source
	CreateBatch(
		ctx context.Context,
		count int,
		source string,
		isSecure bool,
		createdBy string,
		status string,
	) ([]*models.TreasureChest, error)

	// CheckSourceExists checks if a source already exists
	CheckSourceExists(ctx context.Context, source string) (bool, error)

	// GetBySource retrieves all treasure chests with a specific source
	GetBySource(ctx context.Context, source string) ([]*models.TreasureChest, error)

	// GetByQRMatch retrieves a treasure chest by its QR match code
	GetByQRMatch(ctx context.Context, qrMatch string) (*models.TreasureChest, error)

	// GetByID retrieves a treasure chest by its UUID
	GetByID(ctx context.Context, id string) (*models.TreasureChest, error)

	// Update updates an existing treasure chest
	Update(ctx context.Context, chest *models.TreasureChest) error

	// GetByStatus retrieves all chests with a specific status
	GetByStatus(ctx context.Context, status string) ([]*models.TreasureChest, error)
}

// TreasureExplorerRepository defines the interface for explorer data operations
type TreasureExplorerRepository interface {
	// Create creates a new explorer entry (multiple explorers allowed per chest)
	Create(ctx context.Context, explorer *models.TreasureExplorer) error

	// GetByChestID retrieves all explorers for a specific chest
	GetByChestID(ctx context.Context, chestID string) ([]*models.TreasureExplorer, error)
}

// TreasureOwnerRepository defines the interface for owner data operations
type TreasureOwnerRepository interface {
	// Create creates a new owner entry (one owner per chest, unique constraint)
	Create(ctx context.Context, owner *models.TreasureOwner) error

	// GetByChestID retrieves the owner for a specific chest
	GetByChestID(ctx context.Context, chestID string) (*models.TreasureOwner, error)
}
