package postgres

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/mihir/treasure-hunt-backend/internal/models"
	"github.com/mihir/treasure-hunt-backend/internal/repository"
)

// treasureChestRepository implements the TreasureChestRepository interface for PostgreSQL
type treasureChestRepository struct {
	db *sql.DB
}

// NewTreasureChestRepository creates a new PostgreSQL treasure chest repository
func NewTreasureChestRepository(db *sql.DB) repository.TreasureChestRepository {
	return &treasureChestRepository{
		db: db,
	}
}

// Create creates a new treasure chest (ID and QRMatch auto-generated by DB)
func (r *treasureChestRepository) Create(ctx context.Context, chest *models.TreasureChest) error {
	query := `
		INSERT INTO treasure_chest (source, is_secure, status, first_score, subsequent_score, created_by)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id, qr_match, created_at, updated_at
	`

	err := r.db.QueryRowContext(
		ctx,
		query,
		chest.Source,
		chest.IsSecure,
		chest.Status,
		chest.FirstScore,
		chest.SubsequentScore,
		chest.CreatedBy,
	).Scan(&chest.ID, &chest.QRMatch, &chest.CreatedAt, &chest.UpdatedAt)

	if err != nil {
		return fmt.Errorf("failed to create treasure chest: %w", err)
	}

	return nil
}

// CreateBatch creates multiple treasure chests with the same source
func (r *treasureChestRepository) CreateBatch(
	ctx context.Context,
	count int,
	source string,
	isSecure bool,
	firstScore int,
	subsequentScore int,
	createdBy string,
	status string,
) ([]*models.TreasureChest, error) {
	// Start a transaction
	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback()

	query := `
		INSERT INTO treasure_chest (source, is_secure, status, first_score, subsequent_score, created_by)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id, qr_match, source, is_secure, status, first_score, subsequent_score, created_by, created_at, updated_at
	`

	chests := make([]*models.TreasureChest, 0, count)
	for i := 0; i < count; i++ {
		chest := &models.TreasureChest{}
		err := tx.QueryRowContext(
			ctx,
			query,
			source,
			isSecure,
			status,
			firstScore,
			subsequentScore,
			createdBy,
		).Scan(
			&chest.ID,
			&chest.QRMatch,
			&chest.Source,
			&chest.IsSecure,
			&chest.Status,
			&chest.FirstScore,
			&chest.SubsequentScore,
			&chest.CreatedBy,
			&chest.CreatedAt,
			&chest.UpdatedAt,
		)

		if err != nil {
			return nil, fmt.Errorf("failed to create chest %d: %w", i+1, err)
		}

		chests = append(chests, chest)
	}

	// Commit the transaction
	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return chests, nil
}

// GetByQRMatch retrieves a treasure chest by its QR match code
func (r *treasureChestRepository) GetByQRMatch(
	ctx context.Context,
	qrMatch string,
) (*models.TreasureChest, error) {
	query := `
		SELECT id, source, qr_match, is_secure, status, first_score, subsequent_score, created_by, created_at, updated_at
		FROM treasure_chest
		WHERE qr_match = $1
	`

	chest := &models.TreasureChest{}
	err := r.db.QueryRowContext(ctx, query, qrMatch).Scan(
		&chest.ID,
		&chest.Source,
		&chest.QRMatch,
		&chest.IsSecure,
		&chest.Status,
		&chest.FirstScore,
		&chest.SubsequentScore,
		&chest.CreatedBy,
		&chest.CreatedAt,
		&chest.UpdatedAt,
	)

	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("chest with QR match '%s' not found", qrMatch)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get chest by QR match: %w", err)
	}

	return chest, nil
}

// GetByID retrieves a treasure chest by its UUID
func (r *treasureChestRepository) GetByID(
	ctx context.Context,
	id string,
) (*models.TreasureChest, error) {
	query := `
		SELECT id, source, qr_match, is_secure, status, first_score, subsequent_score, created_by, created_at, updated_at
		FROM treasure_chest
		WHERE id = $1
	`

	chest := &models.TreasureChest{}
	err := r.db.QueryRowContext(ctx, query, id).Scan(
		&chest.ID,
		&chest.Source,
		&chest.QRMatch,
		&chest.IsSecure,
		&chest.Status,
		&chest.FirstScore,
		&chest.SubsequentScore,
		&chest.CreatedBy,
		&chest.CreatedAt,
		&chest.UpdatedAt,
	)

	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("chest with ID '%s' not found", id)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get chest by ID: %w", err)
	}

	return chest, nil
}

// GetBySource retrieves all treasure chests with a specific source
func (r *treasureChestRepository) GetBySource(
	ctx context.Context,
	source string,
) ([]*models.TreasureChest, error) {
	query := `
		SELECT id, source, qr_match, is_secure, status, first_score, subsequent_score, created_by, created_at, updated_at
		FROM treasure_chest
		WHERE source = $1
		ORDER BY created_at ASC
	`

	rows, err := r.db.QueryContext(ctx, query, source)
	if err != nil {
		return nil, fmt.Errorf("failed to get chests by source: %w", err)
	}
	defer rows.Close()

	var chests []*models.TreasureChest
	for rows.Next() {
		chest := &models.TreasureChest{}
		err := rows.Scan(
			&chest.ID,
			&chest.Source,
			&chest.QRMatch,
			&chest.IsSecure,
			&chest.Status,
			&chest.FirstScore,
			&chest.SubsequentScore,
			&chest.CreatedBy,
			&chest.CreatedAt,
			&chest.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan chest: %w", err)
		}
		chests = append(chests, chest)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating rows: %w", err)
	}

	return chests, nil
}

// CheckSourceExists checks if a source already exists
func (r *treasureChestRepository) CheckSourceExists(
	ctx context.Context,
	source string,
) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM treasure_chest WHERE source = $1)`

	var exists bool
	err := r.db.QueryRowContext(ctx, query, source).Scan(&exists)
	if err != nil {
		return false, fmt.Errorf("failed to check if source exists: %w", err)
	}

	return exists, nil
}

// Update updates an existing treasure chest
func (r *treasureChestRepository) Update(ctx context.Context, chest *models.TreasureChest) error {
	query := `
		UPDATE treasure_chest
		SET status = $1, updated_at = CURRENT_TIMESTAMP
		WHERE id = $2
		RETURNING updated_at
	`

	err := r.db.QueryRowContext(ctx, query, chest.Status, chest.ID).Scan(&chest.UpdatedAt)
	if err == sql.ErrNoRows {
		return fmt.Errorf("chest with ID '%s' not found", chest.ID)
	}
	if err != nil {
		return fmt.Errorf("failed to update chest: %w", err)
	}

	return nil
}

// GetByStatus retrieves all chests with a specific status
func (r *treasureChestRepository) GetByStatus(
	ctx context.Context,
	status string,
) ([]*models.TreasureChest, error) {
	query := `
		SELECT id, source, qr_match, is_secure, status, first_score, subsequent_score, created_by, created_at, updated_at
		FROM treasure_chest
		WHERE status = $1
		ORDER BY created_at DESC
	`

	rows, err := r.db.QueryContext(ctx, query, status)
	if err != nil {
		return nil, fmt.Errorf("failed to get chests by status: %w", err)
	}
	defer rows.Close()

	var chests []*models.TreasureChest
	for rows.Next() {
		chest := &models.TreasureChest{}
		err := rows.Scan(
			&chest.ID,
			&chest.Source,
			&chest.QRMatch,
			&chest.IsSecure,
			&chest.Status,
			&chest.FirstScore,
			&chest.SubsequentScore,
			&chest.CreatedBy,
			&chest.CreatedAt,
			&chest.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan chest: %w", err)
		}
		chests = append(chests, chest)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating rows: %w", err)
	}

	return chests, nil
}
